import type {NextPage} from 'next';
import Head from 'next/head';
import ToggleDarkmode from '../components/toggle-darkmode';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Tailwind Next DarkMode</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="fixed top-7 right-20">
        <ToggleDarkmode />
      </div>
      <main className="container mx-auto mt-24">
        <h1 className="mb-5 font-lora text-4xl font-medium">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod, perspiciatis.
        </h1>
        <p className="font-lora text-lg">
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Optio doloribus laudantium magni
          sit eaque ducimus dicta enim aspernatur molestias labore dolore ullam, consequatur, quos
          atque vel earum quaerat? Nesciunt aut eum nihil nulla! Molestias in mollitia laboriosam ex
          enim quam voluptatibus dicta corrupti, tenetur consectetur commodi, velit perspiciatis,
          expedita accusamus laborum! Consectetur nisi reiciendis ipsam totam velit esse, provident
          sit mollitia iure non tempore dolor earum, veritatis alias. Sint, consequatur est odit
          voluptatum autem recusandae non consequuntur dolorem quaerat obcaecati minima aperiam.
          Cupiditate exercitationem, molestiae nostrum tenetur eveniet ea saepe qui reiciendis cum
          nesciunt fugiat similique repellat quaerat illum repellendus.
        </p>
      </main>
    </div>
  );
};

export default Home;
